In [1]:
import numpy as np


In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((1,3))

array([[1., 1., 1.]])

In [16]:
np.linspace(0,6,100)

array([0.        , 0.06060606, 0.12121212, 0.18181818, 0.24242424,
       0.3030303 , 0.36363636, 0.42424242, 0.48484848, 0.54545455,
       0.60606061, 0.66666667, 0.72727273, 0.78787879, 0.84848485,
       0.90909091, 0.96969697, 1.03030303, 1.09090909, 1.15151515,
       1.21212121, 1.27272727, 1.33333333, 1.39393939, 1.45454545,
       1.51515152, 1.57575758, 1.63636364, 1.6969697 , 1.75757576,
       1.81818182, 1.87878788, 1.93939394, 2.        , 2.06060606,
       2.12121212, 2.18181818, 2.24242424, 2.3030303 , 2.36363636,
       2.42424242, 2.48484848, 2.54545455, 2.60606061, 2.66666667,
       2.72727273, 2.78787879, 2.84848485, 2.90909091, 2.96969697,
       3.03030303, 3.09090909, 3.15151515, 3.21212121, 3.27272727,
       3.33333333, 3.39393939, 3.45454545, 3.51515152, 3.57575758,
       3.63636364, 3.6969697 , 3.75757576, 3.81818182, 3.87878788,
       3.93939394, 4.        , 4.06060606, 4.12121212, 4.18181818,
       4.24242424, 4.3030303 , 4.36363636, 4.42424242, 4.48484

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(10)

array([0.49269677, 0.27851719, 0.32140286, 0.76879368, 0.91510255,
       0.39724863, 0.5439676 , 0.86755663, 0.90441447, 0.63637432])

In [19]:
np.random.rand(5, 5)

array([[0.09821944, 0.69386737, 0.39809682, 0.25382147, 0.88304023],
       [0.17809861, 0.58274184, 0.40242722, 0.34947815, 0.15917891],
       [0.94045873, 0.66635312, 0.82933412, 0.51089819, 0.43116058],
       [0.52075935, 0.3343011 , 0.42979809, 0.98472977, 0.65131982],
       [0.21188593, 0.09465015, 0.29942096, 0.01590709, 0.98580579]])

In [20]:
np.random.randn(2)

array([-2.13951143,  0.14629433])

In [21]:
np.random.randn(3, 3)

array([[-1.20752236,  0.9710314 ,  0.53307199],
       [ 0.54368803, -0.1406262 ,  0.3052995 ],
       [ 2.85578592,  0.50820573,  0.38726405]])

In [23]:
np.random.randint(1,100, 10)

array([52, 76, 43, 65, 92, 88, 90,  1, 26, 16])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
np.random.randint(0, 50, 10)

array([40,  3, 18, 16, 40,  1,  3, 30, 41, 28])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.max()

24

In [29]:
arr.argmax()

24

In [30]:
arr.min()

0

In [31]:
arr.argmin()

0

In [32]:
arr.shape

(25,)

In [33]:
a = arr.reshape(5,5)

In [34]:
a.shape

(5, 5)

In [37]:
a.dtype

dtype('int32')

In [38]:
from numpy.random import randint
randint(2,10)

2

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[7]

7

In [42]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[1:4]

array([1, 2, 3])

In [44]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [49]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr = arr.copy()

In [57]:
arr[:] = 100

In [58]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr2 = np.array([[4,101,4], [20,30,25], [35,56,78]])

In [60]:
arr2[0]

array([  4, 101,   4])

In [61]:
arr2[0][1]

101

In [62]:
arr2

array([[  4, 101,   4],
       [ 20,  30,  25],
       [ 35,  56,  78]])

In [63]:
arr2[2,1]

56

In [66]:
arr2[2,1]

56

In [69]:
arr2[:2, 1:]

array([[101,   4],
       [ 30,  25]])

In [70]:
arr[:2]

array([100, 100])

In [71]:
arr2[:2]

array([[  4, 101,   4],
       [ 20,  30,  25]])

In [72]:
arr2[:1]

array([[  4, 101,   4]])

In [75]:
arr = np.arange(1, 11)

In [76]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
bol_arr = arr>5

In [82]:
arr[bol_arr]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr[arr<3]

array([1, 2])

In [85]:
arr2 = np.arange(50).reshape(5,10)

In [86]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr2[1:4, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [89]:
arr2[1:3, 2:5]

array([[12, 13, 14],
       [22, 23, 24]])

In [92]:
arr2[1, 3]

13

In [93]:
import numpy as np
arr  = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [95]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [97]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [98]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [100]:
arr/arr

C:\Users\sid\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [101]:
1/arr

C:\Users\sid\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [102]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [104]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [105]:
np.max(arr)

10

In [106]:
np.max(arr)

10

In [107]:
arr.max()

10

In [108]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [109]:
np.log(arr)

C:\Users\sid\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])